### PR TITLE
fix(updateQueue): fmt formatter: copy before iterate

### LINKED ISSUE #727: custom fmt formatter in updateQueue needs a fix
The custom fmt formatter in `updateQueue.hpp` needs to be updated to match the changes in #606 

`get_all_updates` does not return a reference but a copy now (to make it thread safe.

The iterator used to go through the update deque
a) does not keep the deque alive
b) is compared with a new copy of the updates deque when
```
while (it != q.get_all_updates().end())
```

This resulted in a segfault when the formatter is used:
```
Thread 48 (Thread 0x7ff9f0ff9700 (LWP 18356)):
#0  fmt::v6::formatter<updateQueue<std::pair<Hash, std::vector<float, std::allocator<float> > > >, char, void>::format<fmt::v6::basic_format_context<std::back_insert_iterator<fmt::v6::internal::buffer<char> >, char> > (this=this@entry=0x7ff9f0ff87e7, q=..., ctx=...)
    at /opt/kotekan/lib/utils/updateQueue.hpp:166
#1  0x0000000000678045 in fmt::v6::internal::value<fmt::v6::basic_format_context<std::back_insert_iterator<fmt::v6::internal::buffer<char> >, char> >::format_custom_arg<updateQueue<std::pair<Hash, std::vector<float, std::allocator<float> > > >, fmt::v6::formatter<updateQueue<std::pair<Hash, std::vector<float, std::allocator<float> > > >, char, void> > (arg=<optimized out>, parse_ctx=..., ctx=...) at /opt/kotekan/external/fmt/fmt/core.h:739
#2  0x00000000005920ec in fmt::v6::basic_format_arg<fmt::v6::basic_format_context<std::back_insert_iterator<fmt::v6::internal::buffer<char> >, char> >::handle::format (this=<synthetic pointer>, this=<synthetic pointer>, ctx=..., parse_ctx=...)
    at /usr/include/x86_64-linux-gnu/bits/string3.h:53
#3  fmt::v6::internal::custom_formatter<fmt::v6::basic_format_context<std::back_insert_iterator<fmt::v6::internal::buffer<char> >, char> >::operator() (this=<synthetic pointer>, this=<synthetic pointer>, h=...) at /opt/kotekan/external/fmt/fmt/format.h:1890
#4  fmt::v6::visit_format_arg<fmt::v6::internal::custom_formatter<fmt::v6::basic_format_context<std::back_insert_iterator<fmt::v6::internal::buffer<char> >, char> >&, fmt::v6::basic_format_context<std::back_insert_iterator<fmt::v6::internal::buffer<char> >, char> > (arg=..., 
    vis=<synthetic pointer>...) at /opt/kotekan/external/fmt/fmt/core.h:946
#5  fmt::v6::visit_format_arg<fmt::v6::internal::custom_formatter<fmt::v6::basic_format_context<std::back_insert_iterator<fmt::v6::internal::buffer<char> >, char> >&, fmt::v6::basic_format_context<std::back_insert_iterator<fmt::v6::internal::buffer<char> >, char> > (arg=..., 
    vis=...) at /opt/kotekan/external/fmt/fmt/core.h:912
#6  fmt::v6::format_handler<fmt::v6::arg_formatter<fmt::v6::internal::buffer_range<char> >, char, fmt::v6::basic_format_context<std::back_insert_iterator<fmt::v6::internal::buffer<char> >, char> >::on_replacement_field (p=<optimized out>, this=<optimized out>)
    at /opt/kotekan/external/fmt/fmt/format.h:3179
#7  fmt::v6::internal::parse_format_string<false, char, fmt::v6::format_handler<fmt::v6::arg_formatter<fmt::v6::internal::buffer_range<char> >, char, fmt::v6::basic_format_context<std::back_insert_iterator<fmt::v6::internal::buffer<char> >, char> >&> (format_str=..., handler=...)
    at /opt/kotekan/external/fmt/fmt/format.h:2478
#8  0x0000000000592b1c in fmt::v6::vformat_to<fmt::v6::arg_formatter<fmt::v6::internal::buffer_range<char> >, char, fmt::v6::basic_format_context<std::back_insert_iterator<fmt::v6::internal::buffer<char> >, char> > (loc=..., args=..., format_str=..., out=...)
    at /opt/kotekan/external/fmt/fmt/format.h:3441
#9  fmt::v6::internal::vformat_to<char> (args=..., format_str=..., buf=...) at /opt/kotekan/external/fmt/fmt/format.h:3328
#10 fmt::v6::internal::vformat<char> (format_str=..., args=...) at /opt/kotekan/external/fmt/fmt/format.h:3445
#11 0x000000000072b6b8 in fmt::v6::vformat<fmt::v6::basic_string_view<char>, char> (args=..., format_str=<synthetic pointer>...) at /opt/kotekan/lib/core/kotekanLogging.cpp:22
#12 kotekan::kotekanLogging::vinternal_logging (type=type@entry=4, log_prefix=..., format=..., args=...) at /opt/kotekan/lib/core/kotekanLogging.cpp:22
#13 0x00000000006732cc in kotekan::kotekanLogging::internal_logging<updateQueue<std::pair<Hash, std::vector<float, std::allocator<float> > > >, double> (format=..., log_prefix=..., type=4) at /opt/kotekan/lib/utils/visUtil.hpp:257
#14 ReceiveFlags::copy_flags_into_frame (this=0x7fff63c68de0, frame_out=...) at /opt/kotekan/lib/stages/ReceiveFlags.cpp:190
#15 0x00000000006737a8 in ReceiveFlags::main_thread (this=0x7fff63c68de0) at /opt/kotekan/lib/stages/ReceiveFlags.cpp:167
#16 0x0000000000825a20 in execute_native_thread_routine ()
#17 0x00007ffff7bc16ba in start_thread (arg=0x7ff9f0ff9700) at pthread_create.c:333
#18 0x00007ffff3bb841d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:109
```

### PR DESCRIPTION
**Pull request by nritsche**
Closes #727

### CODE REVIEW

File: lib/utils/updateQueue.hpp [hunk 1]
```diff
@@ -160,9 +160,10 @@ struct fmt::formatter<updateQueue<T>> {
...
     template<typename FormatContext>
     auto format(const updateQueue<T>& q, FormatContext& ctx) {
-        auto it = q.get_all_updates().begin();
+        auto all_updates = q.get_all_updates();
+        auto it = all_updates.begin();
         auto pos = ctx.out();
-        while (it != q.get_all_updates().end()) {
+        while (it != all_updates.end()) {
             pos = format_to(pos, "{:f} ", ts_to_double(it->first));
             *it++;
```
Comment (jrs65) [inline lib/utils/updateQueue.hpp:168]: Looks good, and the correct fix to me.

My only comment is that it's probably neater using a range based for loop. It seems I can't apply a suggestion, but something like:

```C++
auto pos = ctx.out();

for (const auto& item : q.get_all_updates()) {
    pos = format_to(pos, "{:f} ", ts_to_double(item.first));
}
```

That's mostly a preference thing, so ignore if you want.

File: lib/utils/updateQueue.hpp [hunk 2]
```diff
@@ -160,12 +160,11 @@ struct fmt::formatter<updateQueue<T>> {
 
     template<typename FormatContext>
     auto format(const updateQueue<T>& q, FormatContext& ctx) {
-        auto it = q.get_all_updates().begin();
+        auto all_updates = q.get_all_updates();
+        auto it = all_updates.begin();
```
Comment (jrs65) [inline lib/utils/updateQueue.hpp:164]:
```suggestion
```
