### PR TITLE
New live to dataset broker tests + fix restClient

### LINKED ISSUE #255: datasetManager: add tests that depend on dataset_broker
depends on split up of ch_acq repo and depends on #201 
`test_dataset_broker.py`:
```
import pytest
import numpy as np
import os.path
import time
from subprocess import Popen
from subprocess import call
import signal

import kotekan_runner

producer_path = "./boost/dataset-broker/dataset_broker_producer"
producer2_path = "./boost/dataset-broker/dataset_broker_producer2"
consumer_path = "./boost/dataset-broker/dataset_broker_consumer"
broker_path = "path/to/dataset_broker.py"

def test_produce_consume():
    if not os.path.isfile(producer_path) or \
      not os.path.isfile(consumer_path) or \
      not os.path.isfile(producer2_path) or \
      not os.path.isfile(broker_path):
        print "Deactivated! Build with -DBOOST_TESTS=ON to activate this test."
        return

    broker = Popen([broker_path])
    time.sleep(1.5)

    try:
      assert call([producer_path]) == 0
      assert call([producer2_path]) == 0
      assert call([consumer_path]) == 0
    finally:
      pid = broker.pid
      os.kill(pid, signal.SIGINT)
      broker.terminate()
```

This doesn't work because the restServer will fail starting in multiple kotekan instances:
```
N_THREADS = 10

def test_produce_consume_async():
    broker = Popen([broker_path])
    time.sleep(1.5)

    p = list()
    p2 = list()
    c = list()

    try:
      for i in range(N_THREADS):
          p.append(Popen([producer_path]))
          p2.append(Popen([producer2_path]))
          c.append(Popen([consumer_path]))

      for i in range(N_THREADS):
          assert p[i].wait() == 0
          assert p2[i].wait() == 0
          assert c[i].wait() == 0
    finally:
      pid = broker.pid
      os.kill(pid, signal.SIGINT)
      broker.terminate()
```

`test_freqslicer_broker.py`:
```
import pytest
import numpy as np
import os
import re
from subprocess import Popen
import time
import signal

import kotekan_runner

broker_path = "../build/ext/src/ch_acq/dataset_broker.py"

import visbuffer
import kotekan_runner


params = {
    'num_elements': 5,
    'num_ev': 0,
    'total_frames': 16,
    'cadence': 10.0,
    'mode': 'default',
    'buffer_depth': 5,
    'freq_ids': range(500, 550),
    'subset_list': [500, 506, 507, 508, 511, 512, 513, 514, 535, 549],
    'use_dataset_manager': True,
    'log_level': "Debug"
}

params['dataset_manager'] = {
    'use_dataset_broker': True,
    'ds_broker_port': 12050,
    'ds_broker_host': "127.0.0.1",
    'register_state_path': "/register-state",
    'register_dataset_path': "/register-dataset",
    'request_ancestor_path': "/request-ancestor",
    'send_state_path': "/send-state"
}

params_fakevis = {
    'num_frames': params['total_frames'],
    'mode': params['mode'],
    'freq_ids': params['freq_ids'],
    'use_dataset_manager': True,
    'wait': False
}

@pytest.fixture(scope="module")
def subset_data(tmpdir_factory):
    if not os.path.isfile(broker_path):
        print "Deactivated! Build with -DBOOST_TESTS=ON to activate this test."
        return

    #run the dataset broker
    broker = Popen([broker_path])
    time.sleep(1.5)

    try:
      tmpdir = tmpdir_factory.mktemp("freqsub_broker_fakevis")

      dump_buffer_gen = kotekan_runner.DumpVisBuffer(
              str(tmpdir))

      test = kotekan_runner.KotekanProcessTester(
          'fakeVis', params_fakevis,
          None,
          dump_buffer_gen,
          params,
      )

      test.run()

      data_gen = dump_buffer_gen.load()

      ### freqSubset ###
      tmpdir = tmpdir_factory.mktemp("freqsub_broker")

      fakevis_buffer_subset = kotekan_runner.FakeVisBuffer(
          num_frames=params['total_frames'],
          mode=params['mode'],
          freq_ids=params['freq_ids'],
          use_dataset_manager=True,
          wait=False,
          dataset_id=data_gen[0].metadata.dataset_id
      )

      dump_buffer_subset = kotekan_runner.DumpVisBuffer(
          str(tmpdir))

      test = kotekan_runner.KotekanProcessTester(
          'freqSubset', {},
          fakevis_buffer_subset,
          dump_buffer_subset,
          params,
      )

      test.run()

      data_subset = dump_buffer_subset.load()

      ### freqSplit ###
      time.sleep(10)
      tmpdir = tmpdir_factory.mktemp("freqsplit_broker")

      fakevis_buffer_split = kotekan_runner.FakeVisBuffer(
          num_frames=params['total_frames'],
          mode=params['mode'],
          freq_ids=params['subset_list'],
          use_dataset_manager=True,
          wait=False,
          dataset_id=data_subset[0].metadata.dataset_id
      )

      dump_buffer_split_lower = kotekan_runner.DumpVisBuffer(
          str(tmpdir))
      dump_buffer_split_higher = kotekan_runner.DumpVisBuffer(
          str(tmpdir))

      test = kotekan_runner.KotekanProcessTester(
          'freqSplit', {},
          fakevis_buffer_split,
          (dump_buffer_split_lower, dump_buffer_split_higher),
          params,
      )

      test.run()

      data_split_lower = dump_buffer_split_lower.load()
      data_split_higher = dump_buffer_split_higher.load()

      ### 2 visWriter processes ###

      tmpdir = tmpdir_factory.mktemp("freqsub_write_lower")

      params_fakevis_write_lower = params_fakevis.copy()
      params_fakevis_write_lower['dataset_id'] = data_split_lower[0].metadata.dataset_id

      # the writer is not given the subset list, it get's it through the broker
      write_buffer_lower = kotekan_runner.VisWriterBuffer(
              str(tmpdir), 'raw', None,
              extra_config={'use_dataset_manager': True})

      test = kotekan_runner.KotekanProcessTester(
          'fakeVis', params_fakevis_write_lower,
          None,
          write_buffer_lower,
          params,
      )

      test.run()

      tmpdir = tmpdir_factory.mktemp("freqsub_write_higher")

      params_fakevis_write_higher = params_fakevis.copy()
      params_fakevis_write_higher['dataset_id'] = data_split_higher[0].metadata.dataset_id

      # the writer is not given the subset list, it get's it through the broker
      write_buffer_higher = kotekan_runner.VisWriterBuffer(
              str(tmpdir), 'raw', None,
              extra_config={'use_dataset_manager': True})

      test = kotekan_runner.KotekanProcessTester(
          'fakeVis', params_fakevis_write_higher,
          None,
          write_buffer_higher,
          params,
      )

      test.run()

      yield [data_gen, data_subset, data_split_lower, data_split_higher,
             write_buffer_lower.load(), write_buffer_higher.load()]
    finally:
      pid = broker.pid
      os.kill(pid, signal.SIGINT)
      broker.terminate()

def test_subset_broker(subset_data):
    data_gen = subset_data[0]
    data_subset = subset_data[1]
    data_split_lower = subset_data[2]
    data_split_higher = subset_data[3]
    data_write_lower = subset_data[4]
    data_write_higher = subset_data[5]

    # basic checks on the data dumped from fakeVis and freqSubset
    subset_lower = [x for x in params['subset_list'] if x < 512]
    subset_higher = [x for x in params['subset_list'] if x >= 512]

    assert len(data_gen) == params['total_frames'] * len(params['freq_ids'])
    assert len(data_subset) == params['total_frames'] \
                               * len(params['subset_list'])
    assert len(data_split_lower) == params['total_frames'] * len(subset_lower)
    assert len(data_split_higher) == params['total_frames'] * len(subset_higher)

    # Count frames by frequency
    counts = [ 0 ] * len(params['subset_list'])
    for frame in data_subset:
      # get freq ids from fakeVis
      fid = int(frame.vis[2].real)
      assert fid in params['subset_list']
      # keep track of number of frames so far
      counts[params['subset_list'].index(fid)] += 1

    assert counts == [ params['total_frames'] ] * len(params['subset_list'])

    # split lower
    counts = [ 0 ] * len(subset_lower)
    for frame in data_split_lower:
      # get freq ids from fakeVis
      fid = int(frame.vis[2].real)
      assert fid in subset_lower
      # keep track of number of frames so far
      counts[subset_lower.index(fid)] += 1

    assert counts == [ params['total_frames'] ] * len(subset_lower)

    # split higher
    counts = [ 0 ] * len(subset_higher)
    for frame in data_split_higher:
      # get freq ids from fakeVis
      fid = int(frame.vis[2].real)
      assert fid in subset_higher
      # keep track of number of frames so far
      counts[subset_higher.index(fid)] += 1

    assert counts == [ params['total_frames'] ] * len(subset_higher)

    # this is what it's really about:
    # check the data the visWriter wrote
    assert len(data_write_lower) == 16
    assert len(data_write_higher) == 16

    # split < 512
    for f in data_write_lower:
        assert len(f) == len(subset_lower)

    counts = [ 0 ] * len(subset_lower)
    for t in range(params['total_frames']):
      for f in range(len(subset_lower)):
        # get freq ids from fakeVis
        fid = int(data_write_lower[t][f].vis[2].real)
        assert fid in subset_lower
        # Check the order
        assert fid == subset_lower[f]
        # keep track of number of frames so far
        counts[subset_lower.index(fid)] += 1

    print counts
    assert counts == [ params['total_frames'] ] * len(subset_lower)

    # split > 512
    for f in data_write_higher:
        assert len(f) == len(subset_higher)

    counts = [ 0 ] * len(subset_higher)
    for t in range(params['total_frames']):
      for f in range(len(subset_higher)):
        # get freq ids from fakeVis
        fid = int(data_write_higher[t][f].vis[2].real)
        assert fid in subset_higher
        # Check the order
        assert fid == subset_higher[f]
        # keep track of number of frames so far
        counts[subset_higher.index(fid)] += 1

    assert counts == [ params['total_frames'] ] * len(subset_higher)
```

### LINKED ISSUE #341: restClient: sporadically lost requests
The restClient some times just looses a request (for example in `test_dataset_manager_rest`).
This might be due to a bug in `libevent 2.1.8` [here](https://github.com/libevent/libevent/issues/733).
Once fixed, reactivate `test_dataset_manager_rest.cpp` in `tests/boost/CMakeList.txt`.

### PR DESCRIPTION
**Pull request by nritsche**
- re-enable `test_dataset_broker`
- re-enable `test_dataset_manager_rest`
- re-enable `test_restclient`
- re-enable `test_freqslicer_broker`
- if comet is installed, use that as the dataset broker in testing
- use random ports everywhere (for parallel CI tests)
- some small fixes from playing around with `cppcheck`
- [x] WIP: fix libevent probvlems in restClient
- [x] merge develop back into this to make sure tests deactivated in 41d69b77b5e4362f30411e4f2f030548d60f4bb1 are running again.
- [x] use watermark to make sure read callback can't starve threads dropping new requests
- [x] fix issue of `bufferevent_read` returning `0` sometimes

Closes #255 
Closes #341 
~Cl0ses #560~ (see issue for details)

### CODE REVIEW

**Comment by nritsche** [comment]
These comments lost connection to this PR because I force-pushed: https://github.com/kotekan/kotekan/commit/60ac1992bb4179866e41d6943666be14848ae1f1#r35724368

File: tests/boost/dataset_broker_producer2.cpp [hunk 1]
```diff
@@ -22,15 +22,20 @@ using json = nlohmann::json;
...
 
 BOOST_FIXTURE_TEST_CASE(_dataset_manager_general, CompareCTypes) {
+    BOOST_CHECK(boost::unit_test::framework::master_test_suite().argc == 2);
+    int broker_port = atoi(boost::unit_test::framework::master_test_suite().argv[1]);
+    BOOST_CHECK(broker_port);
+
     _global_log_level = 5;
     __enable_syslog = 0;
 
     // We have to start the restServer here, because the datasetManager uses it.
```
Comment (jrs65) [inline tests/boost/dataset_broker_producer2.cpp]: Doesn't the dM only need the client?

File: tests/test_dataset_broker.py [hunk 2]
```diff
@@ -7,37 +7,66 @@
...
+from subprocess import call, Popen
+
 producer_path = "../build/tests/boost/dataset_broker_producer"
 producer2_path = "../build/tests/boost/dataset_broker_producer2"
 consumer_path = "../build/tests/boost/dataset_broker_consumer"
-broker_path = "../build/ext/src/ch_acq/dataset_broker.py"
 
 
 def test_produce_consume():
+    broker_path = [
```
Comment (jrs65) [inline tests/test_dataset_broker.py]: Can't this just find `comet` in the current `PATH`. If you're willing to restrict to Python 3, then `shutil.which("comet")` will do that.

File: tests/test_dataset_broker.py [hunk 3]
```diff
@@ -7,37 +7,66 @@
...
+        broker_path = broker_path[0]
+
+    with tempfile.NamedTemporaryFile(mode="w") as f_out:
+        # Start comet with a random port
+        broker = Popen(
+            [broker_path, "-p", "0", "--recover", "False"], stdout=f_out, stderr=f_out
+        )
+        time.sleep(3)
+
+        # Find port in the log
```
Comment (jrs65) [inline tests/test_dataset_broker.py]: Ugh.

Can't you just pick a random port in this code and then set the port when you run the broker?

File: tests/test_freqslicer_broker.py [hunk 4]
```diff
@@ -0,0 +1,257 @@
+import pytest
```
Comment (jrs65) [inline tests/test_freqslicer_broker.py]: AFAICT, this test doesn't do what I thought it was going to: check that the state that is registered in the broker is correct and that the dataset_id's the broker has are the ones that appear in the data. Is there a reason, it can't/doesn't do that one?

File: lib/utils/restClient.cpp [hunk 5]
```diff
@@ -71,16 +72,35 @@ void restClient::event_thread() {
         FATAL_ERROR_NON_OO("restClient: Failure creating new event_base.");
     }
 
+    // The event loop will run in this seperate thread. We have to schedule requests from
```
Comment (jrs65) [inline lib/utils/restClient.cpp]: I'm not going to pretend I've read the changes to this file in any detail. What would be good here would be to have much better overview documentation of the structure of this class, and why it needs to be like this. If you were to disappear, I can't imagine how we would maintain this one. Particularly given that there are subtle restrictions on what libevent itself can handle.

File: lib/core/restServer.hpp [hunk 6]
```diff
@@ -231,6 +231,9 @@ class restServer {
      */
     void remove_all_aliases();
 
+    /// The port to use
```
Comment (jrs65) [inline lib/core/restServer.hpp]: Rather than expose this publicly, you might consider keeping it private and binding a public const reference to it during construction. Then it's effectively readonly publicly but can be modified internally during `start`.

File: tests/boost/dataset_broker_producer2.cpp (hunk 1 above)
Comment (jrs65) [reply tests/boost/dataset_broker_producer2.cpp]: I figured this out. It's for the `force-update` I think.

Comment (nritsche) [reply tests/boost/dataset_broker_producer2.cpp]: Correct. I'm adding this to the comment.

File: tests/test_dataset_broker.py (hunk 2 above)
Comment (nritsche) [reply tests/test_dataset_broker.py]: Thanks, that's nice.

File: tests/test_dataset_broker.py (hunk 3 above)
Comment (nritsche) [reply tests/test_dataset_broker.py]: The tests run in parallel on the CI server. So they could pick the same random free port in parallel tests and mysteriously fail.

File: tests/test_freqslicer_broker.py (hunk 4 above)
Comment (nritsche) [reply tests/test_freqslicer_broker.py]: This test is very old, I only reactivated it here. But I guess it was meant to be a high level test, as it doesn't do what you describe directly, but lets visWriter do it and then tests against what ends up on disk.

**Comment by nritsche** [comment]
This adds the following to the `Jenkinsfile` CI tests:
It installs `comet` from https://github.com/chime-experiment/comet
If the installation fails, the (py)tests that depend on it are skipped and the build doesn't fail.
If the installation is successful, some tests are run that use the comet dataset broker.

File: lib/utils/datasetState.cpp [hunk 7]
```diff
@@ -36,7 +36,6 @@ std::ostream& operator<<(std::ostream& out, const datasetState& dt) {
     return out;
 }
 
-// TODO: this is a very weird place for this routine to be. Put it somewhere more sane.
```
Comment (jrs65) [inline lib/utils/datasetState.cpp]: It's still in a weird place. Did you just move this into an issue?

File: lib/utils/restClient.hpp [hunk 8]
```diff
@@ -19,16 +19,53 @@
...
  * @class restClient
  * @brief REST client: Send REST messages to a server and maybe get a reply.
  *
  * This class supports sending GET messages and POST messages with json data
  * using libevent and provides access to data from the reply of the server.
  *
+ * Implementation
+ * ==============
+ *
+ * There is an event loop running int the main_thread() that gets started by the constructor.
```
Comment (jrs65) [inline lib/utils/restClient.hpp]:
```suggestion
 * There is an event loop running in the main_thread() that gets started by the constructor.
```

File: lib/utils/datasetState.cpp (hunk 7 above)
Comment (nritsche) [reply lib/utils/datasetState.cpp]: Where else should it be? I thought that now that it's all in `datasetState.*` we are good, because that's the only place where it is used.

Comment (nritsche) [reply lib/utils/datasetState.cpp]: https://github.com/kotekan/kotekan/issues/601

**Comment by nritsche** [comment]
@jrs65 I think this is ready to merge. Do you approve?

**Comment by jrs65** [comment]
Approved!
